version: '3.4'

services:
  sample.api:
    image: ${DOCKER_REGISTRY-}sampleapi
    build:
      context: .
      dockerfile: Sample.API/Dockerfile
    ports:
      - 4001:80
    depends_on:
      - db

  db:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"